# Generated by Django 5.1.3 on 2025-11-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='lc_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
