# Generated by Django 5.1.3 on 2025-11-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_signup_options_remove_signup_user_signup_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='discord_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
