# Generated by Django 5.1.3 on 2025-11-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsa_queue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="capacity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="signup",
            name="lc_level",
            field=models.CharField(
                blank=True,
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=10,
                null=True,
            ),
        ),
    ]
